
const status = {
    "PENDING": "PENDING",
    "DOUGH_PENDING": "DOUGH_PENDING",
    "DOUGH_PROGRESS": "DOUGH_PROGRESS",
    "DOUGH_COMPLETED": "DOUGH_COMPLETED",
    "TOPPINGS_PENDING": "TOPPINGS_PENDING",
    "TOPPINGS_PROGRESS": "TOPPINGS_PROGRESS",
    "TOPPINGS_COMPLETED": "TOPPINGS_COMPLETED",
    "BAKING_PENDING": "BAKING_PENDING",
    "BAKING_PROGRESS": "BAKING_PROGRESS",
    "BAKING_COMPLETED": "BAKING_COMPLETED",
    "SERVING_PENDING": "SERVING_PENDING",
    "SERVING_PROGRESS": "SERVING_PROGRESS",
    "SERVING_COMPLETED": "SERVING_COMPLETED",
    "COMPLETED": "COMPLETED",
    "ERROR": "ERROR"
  };